config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/", to: "welcome#index"
  resources :users
  get '/users/:id/roles', to: 'users#editrole'
  post '/users/:id/roles', to: 'users#updaterole'
  get '/users/:id/password', to: 'users#editpassword'
  patch '/users/:id/password', to: 'users#updatepassword'
  get '/users/:id/temppass', to: 'users#createtemppassword'
  get '/profile', to: 'users#profile'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :storage_facilities do
    get 'test', to: 'storage_facilities#test'
  end

  resources :animals do
    resources :images, except: [ :index, :show, :edit, :update ]
  end

  resources :registrations

  resources :inventory_transactions, except: :destroy

  resources :fees

  resources :breeds

  resources :skus

  resources :purchases , only: [ :index, :show ] do
    post 'invoice', to: 'purchases#invoice'
    post 'paid', to: 'purchases#paid'
    post 'shipped', to: 'purchases#shipped'
    post 'delivered', to: 'purchases#delivered'
    post 'reset', to: 'purchases#reset'
    post 'administrative', to: 'purchases#administrative'
    post 'payment', to: 'purchases#payment'
    resources :line_items, except: :index
    resources :shipments, except: [:index, :delete]
  end

  get '/commissions', to: 'commissions#index'
  post '/users/:user/commission', to: 'commissions#create' #API
  delete '/users/:user/commission', to: 'commissions#destroy' #API

  get '/session/new', to: 'session#new'
  post '/cart/update', to: 'cart#update'
  get '/cart', to: 'cart#show'
  get '/cart/checkout', to: 'cart#checkout'

  get '/settings', to: "settings#index"
  post '/settings', to: "settings#update"

  get '/addresses/:id', to: "addresses#show", as: 'address'

  #errors
  match '/401', to: 'errors#unauthorised', via: :all

end

app/models/animal.rb
class Animal < ApplicationRecord
  belongs_to :owner, class_name: 'User'
  belongs_to :breed
  belongs_to :sire, class_name: 'Animal', optional: true
  belongs_to :dam, class_name: 'Animal', optional: true


  has_many :registrations
  has_many :skus
  has_many :images

  validates :name, presence: true
  validates :is_male, inclusion: [true, false]

  validate :sire_must_be_male, :dam_must_be_female, :sire_must_match_breed, :dam_must_match_breed

  def get_drop_down_name
    "#{name} - #{owner.first_name} #{owner.last_name}"
  end

  def children #acts as has_many association with 2 foreign keys
    Animal.where('sire_id = ? or dam_id = ?', self.id, self.id)
  end

  private

  def sire_must_be_male
    return unless sire.present?
    errors.add(:sire, "sire must be male") unless sire.is_male
  end

  def dam_must_be_female
    return unless dam.present?
    errors.add(:dam, "dam must be female") if dam.is_male
  end

  def sire_must_match_breed
    return unless sire.present?
    errors.add(:sire, "sire must be a #{breed.breed_name}") unless sire.breed.id == breed.id
  end

  def dam_must_match_breed
    return unless dam.present?
    errors.add(:dam, "dam must be a #{breed.breed_name}") unless dam.breed.id == breed.id
  end
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  protect_from_forgery except: :repl

  def secure
    true
  end

  def index
    @animals = Animal.all.preload(:owner, :registrations)
    @breeds = Breed.all.preload(:registrars)
  end

  def show
    @animal = Animal.find(params[:id])
    @skus = Sku.where(animal: @animal)
  end

  def new
    @animal = Animal.new
  end

  def edit
    @animal = Animal.find(params[:id])
  end

  def create
    @animal = Animal.new(animal_params)

    put_data_in_animal
    put_registrations

    if @animal.save
      redirect_to @animal
    else
      render :new
    end
  end

  def update
    @animal = Animal.find(params[:id])

    @animal.update(animal_params)
    put_data_in_animal
    put_registrations

    if @animal.save
      redirect_to @animal
    else
      render :edit
    end
  end

  def destroy
    @animal = Animal.find(params[:id])
    @animal.destroy
    redirect_to Animal
  end

  protected

  def put_data_in_animal
    @animal.owner = User.find animal_params[:owner_id]
  end

  def animal_params
    params.require(:animal).permit(
      :name, :description, :notes, :owner_id, :breed_id, :private_herd_number, :dna_number, :is_male, :dam_id, :sire_id, :date_of_birth
    )
  end

  def registration_params (registrar)
    params.require(:registrations).require(registrar.name.parameterize).permit(:registration, :ai_certification).merge({registrar: registrar})
  end

  def put_registrations
    @animal.breed.registrars.each do |registrar|
      registration = @animal.registrations.where(registrar: registrar).first #there should only be one!
      registration ||= Registration.new()
      registration.assign_attributes registration_params(registrar)
      unless registration.registration.empty? && registration.ai_certification.empty?
        @animal.registrations << registration
      else
        registration.destroy!
      end
    end
  end

end

app/helpers/animals_helper.rb
module AnimalsHelper
  def use_existing_breed

  end

  def use_new_breed

  end

  def humanize_registrations_registration(registration)
    case registration.count
    when 0
      ""
    when 1
      registration.first.registration
    else
      "Multiple registrations! " + registration.reduce("[") do |sum,reg|
        sum + reg.id.to_s + ","
      end + "]"
    end
  end

  def humanize_registrations_ai_certification(registration)
    case registration.count
    when 0
      ""
    when 1
      registration.first.ai_certification
    else
      "Error"
    end
  end
end

app/views/animals/_animal_form.erb
<%= form_for @animal do |a| %>
    <div>
      <%= a.label :name, get_field_errors(@animal, :name) %>
      <%= a.text_field :name %>
    </div>
    <div>
      <%= a.label :is_male, "Gender" %>
      <%= a.select :is_male, {male: true, female: false} %>
    </div>
    <div>
      <%= a.label :description, get_field_errors(@animal, :description) %>
      <%= a.text_field :description %>
    </div>
    <div>
      <%= a.label :notes, get_field_errors(@animal, :notes) %>
      <%= a.text_field :notes %>
    </div>
    <div>
      <%= a.label :private_herd_number, get_field_errors(@animal, :private_herd_number) %>
      <%= a.text_field :private_herd_number %>
    </div>
    <div>
      <%= a.label :dna_number, get_field_errors(@animal, :dna_number) %>
      <%= a.text_field :dna_number %>
    </div>
    <div>
      <%= a.label :owner_id, get_field_errors(@animal, :owner_id) %>
      <%= a.collection_select :owner_id, User.all, :id, :get_name %>
    </div>
    <div>
      <%= a.label :breed_id, get_field_errors(@animal, :breed_id) %>
      <%= a.collection_select :breed_id, Breed.all, :id, :breed_name %>
    </div>
    <div>
      <%= a.label :sire_id, get_field_errors(@animal, :sire_id) %>
      <%= a.collection_select :sire_id, Animal.where(is_male: true), :id, :name, include_blank: "Sire is not in system" %>
    </div>
    <div>
      <%= a.label :dam_id, get_field_errors(@animal, :dam_id) %>
      <%= a.collection_select :dam_id, Animal.where(is_male: false), :id, :name, include_blank: "Dam is not in system" %>
    </div>
    <div>
      <%= a.label :date_of_birth %>
      <%= a.date_select :date_of_birth, include_blank: true, start_year: Date.current.year, end_year: 1960 %>
    </div>
    <div id="registryinfo">
      <!-- empty for JS --!>
    </div>
    <%= a.submit %>
<% end %>

app/views/animals/edit.erb
<%= render 'animal_form' %>

app/views/animals/index.erb
<%= link_to 'Add Animal', new_animal_path %>
<ul>
  <% @breeds.each do |breed| %>
    <li><a href="#<%= "go-to-#{breed.breed_name.parameterize}" %>"><%= breed.breed_name %></a></li>
  <% end %>
</ul>
<% @breeds.each do |breed| %>
  <% @registrars = breed.registrars %>
  <h2 id="<%= "go-to-#{breed.breed_name.parameterize}" %>" ><%= breed.breed_name %></h2>
  <a href="#top">Top of page</a>
  <table>
    <thead>
    <tr>
      <th>Animal</th>
      <th>ID</th>
      <th>Private Herd Number</th>
      <th>DNA Number</th>
      <% @registrars.each do |registrar| %>
        <th><%= registrar.name %> registration</th>
        <th><%= registrar.name %> AI Certification</th>
      <% end %>
      <th>Owner</th>
    </tr>
    </thead>
    <tbody>
    <% @animals.where(breed: breed).each do |animal| %>
      <% cache animal do %>
        <tr>
          <td><%= link_to animal.name, animal %></td>
          <td><%= animal.id %></td>
          <td><%= animal.private_herd_number ? animal.private_herd_number : "" %></td>
          <td><%= animal.dna_number ? animal.dna_number : "" %></td>
          <% @registrars.each do |registrar| %>
            <% registration = animal.registrations.where(registrar: registrar) %>
            <td><%= humanize_registrations_registration registration %></td>
            <td><%= humanize_registrations_ai_certification registration%></td>
          <% end %>
            <td><%= link_to animal.owner.get_name, animal.owner %></td>
        </tr>
      <% end %>
    <% end %>
    </tbody>
  </table>
<% end %>

app/views/animals/new.erb
<%= render 'animal_form' %>

app/views/animals/show.erb
<% if flash[:notice] %>
  <div>
    <p>
      <%= flash[:notice] %>
    </p>
  </div>
<% end %>
<div>
  <%= link_to 'All Animals', animals_path %>
</div>
<div>
  <%= link_to 'Edit Animal', edit_animal_path(@animal) %>
</div>
<div>
  <%= link_to 'Add Image', new_animal_image_path(@animal) %>
</div>
<div>
  <%= link_to 'Remove Animal', @animal, method: :delete, data: { confirm: 'Are you sure you want to remove this animal?' } %>
</div>
<% if @animal.images.count > 0 %>
  <div>
    <h3>Images</h3>
    <% @animal.images.each do |image| %>
      <img src="<%= image.url %>">
    <% end %>
  </div>
<% end %>
<div>
  Breed: <%= @animal.breed.breed_name unless @animal.breed.nil? %>
</div>
<div>
  Name: <%= @animal.name %>
</div>
<div>
  Gender: <%= @animal.is_male ? "Male" : "Female" %>
</div>
<div>
  Description Override: <%= @animal.description %>
</div>
<div>
  Notes Override: <%= @animal.notes %>
</div>
<div>
  Owner Name: <%= "#{@animal.owner.first_name} #{@animal.owner.last_name}" %>
</div>
<div>
  Private Herd Number: <%= @animal.private_herd_number ? @animal.private_herd_number : "N/A" %>
</div>
<div>
  DNA Number: <%= @animal.dna_number ? @animal.dna_number : "N/A" %>
</div>
<% if @animal.sire %>
  <div>
    Sire: <%= link_to @animal.sire.name, @animal.sire %>
  </div>
<% else %>
  <div>
    Sire: Sire is not in system
  </div>
<% end %>
<% if @animal.dam %>
  <div>
    Dam: <%= link_to @animal.dam.name, @animal.dam %>
  </div>
<% else %>
  <div>
    Dam: Dam is not in system
  </div>
<% end %>
<div>
  Date of Birth: <%= @animal.date_of_birth ? @animal.date_of_birth : "N/A" %>
</div>
<div>
  Registrations
  <table>
    <thead>
      <tr>
        <th>Registrar</th>
        <th>Registration</th>
        <th>AI Certification</th>
        <th>Notes</th>
      </tr>
    </thead>
    <tbody>
      <% @animal.registrations.each do |registration| %>
        <tr>
          <td><%= registration.registrar.name %></td>
          <td><%= link_to registration.registration, registration %></td>
          <td><%= registration.ai_certification %></td>
          <td><%= registration.note %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div>
  all stock
  <table>
    <thead>
    <tr>
      <th>Sku</th>
      <th>Quantity</th>
      <th>Private</th>
      <th>Semen Type</th>
      <th>Price Per Unit</th>
      <th>Semen Count</th>
      <th>Storage Facility</th>
      <th>Seller</th>
      <th>Add To Cart</th>
    </tr>
    </thead>
    <tbody>
    <% @skus.each do |t| %>
        <tr>
          <td><%= link_to "SKU #{t.id}", sku_path(t) %></td>
          <td><%= t.quantity %></td>
          <td><%= t.private %></td>
          <td><%= t.semen_type %></td>
          <td>$<%= t.price_per_unit %></td>
          <td><%= t.semen_count %></td>
          <td><%= t.storagefacility.name %></td>
          <td><%= t.seller.get_name %></td>
          <td><input type="number" id="<%= t.id %>_quantity" value="1"></input><button class="add_to_cart" data-sku-id="<%= t.id %>">Add sku#<%= t.id %> to Cart</button></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>