config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/", to: "welcome#index"
  resources :users
  get '/users/:id/roles', to: 'users#editrole'
  post '/users/:id/roles', to: 'users#updaterole'
  get '/users/:id/password', to: 'users#editpassword'
  patch '/users/:id/password', to: 'users#updatepassword'
  get '/users/:id/temppass', to: 'users#createtemppassword'
  get '/profile', to: 'users#profile'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :storage_facilities do
    get 'test', to: 'storage_facilities#test'
  end

  resources :animals do
    resources :images, except: [ :index, :show, :edit, :update ]
  end

  resources :registrations

  resources :inventory_transactions, except: :destroy

  resources :fees

  resources :breeds

  resources :skus

  resources :purchases , only: [ :index, :show ] do
    post 'invoice', to: 'purchases#invoice'
    post 'paid', to: 'purchases#paid'
    post 'shipped', to: 'purchases#shipped'
    post 'delivered', to: 'purchases#delivered'
    post 'reset', to: 'purchases#reset'
    post 'administrative', to: 'purchases#administrative'
    post 'payment', to: 'purchases#payment'
    resources :line_items, except: :index
    resources :shipments, except: [:index, :delete]
  end

  get '/commissions', to: 'commissions#index'
  post '/users/:user/commission', to: 'commissions#create' #API
  delete '/users/:user/commission', to: 'commissions#destroy' #API

  get '/session/new', to: 'session#new'
  post '/cart/update', to: 'cart#update'
  get '/cart', to: 'cart#show'
  get '/cart/checkout', to: 'cart#checkout'

  get '/settings', to: "settings#index"
  post '/settings', to: "settings#update"

  get '/addresses/:id', to: "addresses#show", as: 'address'

  #errors
  match '/401', to: 'errors#unauthorised', via: :all

end

app/controllers/inventory_transactions_controller.rb
class InventoryTransactionsController < ApplicationController

  def index
    @transactions = InventoryTransaction.all.preload(sku: :animal)
  end

  def new
    @transaction = InventoryTransaction.new
    if params[:sku_id]
      @transaction.sku = Sku.find(params[:sku_id])
    else
      @transaction.sku = Sku.new
    end
  end

  def show
    @transaction = InventoryTransaction.find(params[:id])
  end

  def create
    InventoryTransaction.transaction do
      @transaction = InventoryTransaction.new(get_params.merge(sku: get_sku))
      if @transaction.save and @transaction.sku.valid?
        redirect_to @transaction
      else
        render :new
        raise ActiveRecord::Rollback
      end
    end
  end

  def edit
    @transaction = InventoryTransaction.find params[:id]
  end

  def update
    @transaction = InventoryTransaction.find params[:id]
    InventoryTransaction.transaction do
      @transaction.update(get_params.merge(sku: get_sku))
      if @transaction.save and @transaction.sku.valid?
        redirect_to @transaction
      else
        render :edit
        raise ActiveRecord::Rollback
      end
    end
  end

  protected

  def get_params
    params.require(:inventory_transaction).permit(:quantity)
  end

  def get_sku
    sku_params = params.require(:inventory_transaction).require(:sku).permit(:private, :semen_type, :semen_count, :price_per_unit, :animal_id, :storagefacility_id, :seller_id, :cost_per_unit, :cane_code, :has_percent)
    sku_params.transform_values! { |value| value == "" ? nil : value }
    Sku.find_or_create_by(sku_params)
  end

end

app/helpers/inventory_transactions_helper.rb
module InventoryTransactionsHelper
end

app/views/inventory_transactions/_cpu_commission.erb
<%# Assuming the order is cost_per_unit then commission %>
<% if transaction.cost_per_unit %>
  <td><%= number_to_currency(transaction.cost_per_unit) %></td>
  <td><%= "%.2f" % ((transaction.price_per_unit - transaction.cost_per_unit) / transaction.price_per_unit * 100) %>%</td>
<% else %>
  <td><%= number_to_currency(transaction.price_per_unit - (transaction.price_per_unit / transaction.seller.commission.commission_percent) )%></td>
  <td><%= "%.2f" % transaction.seller.commission.commission_percent %>%</td>
<% end %>

app/views/inventory_transactions/_inventory_form.erb
<%= form_for @transaction do |f| %>
    <div>
      <%= f.label :quantity, get_field_errors(@transaction, :quantity) %>
      <%= f.text_field :quantity %>
    </div>
    <em>Sku properties!</em>
    <p>These fields are used to select the appropiate SKU for this transaction, if no matching SKU is found a new one will be made.
      <% if @transaction.sku and @transaction.sku.id %>
        If you are trying to change the SKU's properties for all transactions attached you should <%= link_to "edit this SKU", edit_sku_path(@transaction.sku) %> instead.
      <% end %>
    </p>

    <%= render 'skus/form', sku: @transaction.sku, f: f, nosubmit: true, fieldsfor: true %>

    <div>
      <%= f.submit %>
    </div>
<% end %>

app/views/inventory_transactions/edit.erb
<%= render 'inventory_form' %>

app/views/inventory_transactions/index.erb
<%= link_to "New", new_inventory_transaction_path %>
<table>
  <thead>
    <th colspan=3 class="nosort"></th>
    <th>quantity</th>
    <th>Sku</th>
    <th>Animal</th>
    <th>Updated</th>
    <th>Created</th>
  </thead>
  <tbody>
    <% @transactions.order(updated_at: :desc).each do |transaction| %>
      <% cache transaction do %>
        <tr>
          <td><%= link_to "Show", transaction %></td>
          <td><%= link_to "Edit", edit_inventory_transaction_path(transaction) %></td>
          <td><%= link_to "Destroy", transaction, method: :delete, data: { confirm: "Are you sure?" } %></td>
          <td><%= transaction.quantity %></td>
          <td><%= link_to transaction.sku.id, transaction.sku %></td>
          <td><%= link_to transaction.sku.animal.name, transaction.sku.animal %></td>
          <td><%= transaction.updated_at %></td>
          <td><%= transaction.created_at %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/inventory_transactions/new.erb
<%= render 'inventory_form' %>

app/views/inventory_transactions/show.erb
<%= link_to "back", InventoryTransaction %>
<%= link_to "edit", edit_inventory_transaction_path(@transaction) %>
<table class="nosort">
  <thead>
    <th>Transaction ID</th>
    <th>Sku</th>
    <th>Quantity</th>
    <th>Created at</th>
    <th>Updated at</th>
  </thead>
  <tbody>
    <tr>
      <td><%= @transaction.id %></td>
      <td><%= link_to @transaction.sku.id, @transaction.sku %></td>
      <td><%= @transaction.quantity %></td>
      <td><%= @transaction.created_at %></td>
      <td><%= @transaction.updated_at %></td>
    </tr>
  </tbody>
</table>