config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/", to: "welcome#index"
  resources :users
  get '/users/:id/roles', to: 'users#editrole'
  post '/users/:id/roles', to: 'users#updaterole'
  get '/users/:id/password', to: 'users#editpassword'
  patch '/users/:id/password', to: 'users#updatepassword'
  get '/users/:id/temppass', to: 'users#createtemppassword'
  get '/profile', to: 'users#profile'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :storage_facilities do
    get 'test', to: 'storage_facilities#test'
  end

  resources :animals do
    resources :images, except: [ :index, :show, :edit, :update ]
  end

  resources :registrations

  resources :inventory_transactions, except: :destroy

  resources :fees

  resources :breeds

  resources :skus

  resources :purchases , only: [ :index, :show ] do
    post 'invoice', to: 'purchases#invoice'
    post 'paid', to: 'purchases#paid'
    post 'shipped', to: 'purchases#shipped'
    post 'delivered', to: 'purchases#delivered'
    post 'reset', to: 'purchases#reset'
    post 'administrative', to: 'purchases#administrative'
    post 'payment', to: 'purchases#payment'
    resources :line_items, except: :index
    resources :shipments, except: [:index, :delete]
  end

  get '/commissions', to: 'commissions#index'
  post '/users/:user/commission', to: 'commissions#create' #API
  delete '/users/:user/commission', to: 'commissions#destroy' #API

  get '/session/new', to: 'session#new'
  post '/cart/update', to: 'cart#update'
  get '/cart', to: 'cart#show'
  get '/cart/checkout', to: 'cart#checkout'

  get '/settings', to: "settings#index"
  post '/settings', to: "settings#update"

  get '/addresses/:id', to: "addresses#show", as: 'address'

  #errors
  match '/401', to: 'errors#unauthorised', via: :all

end

app/models/fee.rb
class Fee < ApplicationRecord
  enum fee_type: {
    'Release': 0,
    'Handling': 1,
    'Tank Rental': 2,
    'Packaging Fee': 3
  }

  belongs_to :storage_facility

  validates :price, presence: true
  validates :fee_type, presence: true
end

app/controllers/fees_controller.rb
class FeesController < ApplicationController

  def index
    @fees = Fee.all
  end

  def show
    @fee = Fee.find(params[:id])
  end

  def new
    @fee = Fee.new
  end

  def edit
    @fee = Fee.find(params[:id])
  end

  def create
    @fee = Fee.create fee_params
    put_facility_in_fee

    respond_to do |format|
      if @fee.save
        format.html { redirect_to @fee, notice: "Fee was successfully crated." }
        format.json { render :show, status: :created, location: @fee }
      else
        format.html { render :new }
        format.json { render json: @fee.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @fee = Fee.find(params[:id])
    @fee.update fee_params
    put_facility_in_fee

    respond_to do |format|
      if @fee.save
        format.html { redirect_to @fee, notice: "Fee was successfully updated." }
        format.json { render :show, status: :ok, location: @fee }
      else
        format.html { render :edit }
        format.json { render json: @fee.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @fee = Fee.find(params[:id])
    @fee.destroy
    respond_to do |format|
      format.html { redirect_to Fee}
      format.json { head :no_content }
    end
  end

  protected

  def fee_params
    params.require(:fee).permit(
      :price, :fee_type, :storage_facility_id
    )
  end

  def put_facility_in_fee
    @fee.storage_facility = StorageFacility.find fee_params[:storage_facility_id]
  end

end

app/helpers/fees_helper.rb
module FeesHelper
end

app/views/fees/_fee_form.erb
<%= form_for @fee do |f| %>
  <div>
    <%= f.label :price, get_field_errors(@fee, :cost) %>
    <%= f.text_field :price %>
  </div>
  <div>
    <%= f.label :fee_type, get_field_errors(@fee, :fee_type) %>
    <%= f.select :fee_type, Fee.fee_types.keys %>
  </div>
  <div>
    <%= f.label :storage_facility_id, get_field_errors(@fee, :storage_facility) %>
    <%= f.collection_select :storage_facility_id, StorageFacility.all, :id, :name %>
  </div>
  <%= f.submit %>
<% end %>

app/views/fees/edit.erb
<%= render 'fee_form' %>

app/views/fees/index.erb
<%= link_to 'Add Fee', new_fee_path %>
<table>
  <thead>
    <tr>
      <th class="nosort"></th>
      <th>Facility</th>
      <th>Price</th>
      <th>Type</th>
    </tr>
  </thead>
  <tbody>
    <% @fees.each do |f| %>
      <tr>
        <td><%= link_to 'View', f %></td>
        <td><%= link_to f.storage_facility.name, f.storage_facility %></td>
        <td>$<%= f.price %></td>
        <td><%= f.fee_type %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/fees/new.erb
<%= render 'fee_form' %>

app/views/fees/show.erb
<div>
  <div>
    <%= link_to 'All fees', fees_path %>
  </div>
  <div>
    <%= link_to 'Edit', edit_fee_path(@fee) %>
  </div>
  <div>
    Cost: <%= @fee.price %>
  </div>
  <div>
    Type: <%= @fee.fee_type %>
  </div>
  <div>
    Facility: <%= link_to @fee.storage_facility.name, @fee.storage_facility %>
  </div>
</div>